version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --save "" --appendonly no
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test:  ["CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
