global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 1s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 1s
    api_version: v1

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: my-service
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - my-service-0:8080
    - my-service-1:8080
    - my-service-2:8080
    - my-service-3:8080
    - my-service-4:8080
